# src/agents/tactician.py
import time
from langchain_core.messages import HumanMessage
from src.state import RepoState
from src.tools.gitops import GitOps
from src.utils.workspace import load_artifact
from src.utils.config import cfg

def tactician_node(state: RepoState) -> RepoState:
    """
    The Git Tactician Agent.
    It reviews artifacts generated by other agents (like Refactor Plans)
    and executes the necessary Git operations (Branching, Committing).
    """
    print("--- ⚔️  Tactician: Reviewing Operations ---")
    
    repo_path = state.get("repo_path", cfg.get("paths.repo_root"))
    git_ops = GitOps(repo_path)
    
    artifacts = state.get("artifacts", [])
    actions_taken = []
    
    # 1. Check for Refactor Plans (from Steward)
    refactor_plans = [a for a in artifacts if a["type"] == "refactor_plan"]
    
    if refactor_plans:
        # Create a specific branch for the auto-fixes
        branch_name = f"reporanger/refactor-{int(time.time())}"
        print(f"    Creating branch: {branch_name}")
        git_ops.switch_branch(branch_name, create_new=True)
        
        for plan in refactor_plans:
            # In a real app, we would parse the markdown to extract the code block.
            # For now, we assume the artifact file contains the cleaner code or we just commit the plan.
            # Let's verify we can read the plan.
            content = load_artifact(plan["file_path"])
            
            # Action: We commit the plan as a TODO file for the human developer
            # (Applying raw LLM code directly is risky without a dedicated Patcher tool)
            filename = f"REFACTOR_PLAN_{plan['id']}.md"
            with open(f"{repo_path}/{filename}", "w") as f:
                f.write(content)
            
            git_ops.commit_changes(f"chore: Add refactor plan for {plan['description']}", [filename])
            actions_taken.append(f"Created branch '{branch_name}' with refactor plan.")

    # 2. Check for Documentation (from Scribe)
    # Usually, we want docs to go into the current PR, not a new branch.
    doc_artifacts = [a for a in artifacts if a["type"] == "markdown_doc" and a["created_by"] == "scribe"]
    if doc_artifacts:
        # We just note that these are ready for the user to copy-paste into the PR description
        actions_taken.append("PR Documentation is ready in artifacts.")

    if not actions_taken:
        print("    No actionable artifacts found. Standing by.")
    
    print("--- ⚔️  Tactician: Operations Complete ---")

    return {
        "messages": [HumanMessage(content=f"Tactician executed: {', '.join(actions_taken)}")]
    }